---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: MCP Demo
spec:

  # MCP Servers
  - name: Ticket MCP Server
    type: mcp.Server
    url: http://host.docker.internal:8080
    transport: sse

  - name: Agility MCP Server
    type: mcp.Server
    url: https://api.staging.digital.ai/agilitymcp/v1/mcp
    headers:
      X-Agility-Bearer: !value AGILITY_KEY
      X-Agility-Host: https://www7.v1host.com/V1Production

  - name: Release MCP Server
    type: mcp.Server
    url: http://host.docker.internal:8000/mcp

    # Gemini Models
  - name: Gemini 2.5 Pro
    type: mcp.GeminiModel
    apiKey: !value GEMINI_API_KEY
    model: gemini-2.5-pro

  - name: Gemini 2.5 Flash
    type: mcp.GeminiModel
    apiKey: !value GEMINI_API_KEY
    model: gemini-2.5-flash

  - name: Gemini 2.5 Flash-Lite
    type: mcp.GeminiModel
    apiKey: !value GEMINI_API_KEY
    model: gemini-2.5-flash-lite

  # Demo Templates
  - template: MCP Ticket Sample
    phases:
      - phase: List tickets
        tasks:
          - name: Get tickets
            type: mcp.CallTool
            server: Ticket MCP Server
            tool: list_tickets
          - name: Get single ticket
            type: mcp.CallTool
            server: Ticket MCP Server
            tool: get_ticket
            input: |
              {"id": "TICKET-001"}
          - name: OK?
            type: xlrelease.GateTask

  - template: MCP Agility Sample
    phases:
      - phase: MCP
        tasks:
          - name: List Agility tools
            type: mcp.ListTools
            server: Agility MCP Server
          - name: Get current Agility user
            type: mcp.CallTool
            server: Agility MCP Server
            tool: get_current_user
          - name: OK?
            type: xlrelease.GateTask
            owner: admin

  - template: MCP Release Sample
    phases:
      - phase: List releases
        tasks:
          - name: List Release tools
            type: mcp.ListTools
            server: Release MCP Server
          - name: Get releases
            type: mcp.CallTool
            server: Release MCP Server
            tool: list_releases
            input: |
              {
                "request": {}
              }
          - name: OK?
            type: xlrelease.GateTask
            owner: admin

  - template: List tools
    phases:
      - phase: List tools
        tasks:
          - name: List Ticket tools
            type: mcp.ListTools
            server: Ticket MCP Server
          - name: List Release tools
            type: mcp.ListTools
            server: Release MCP Server
          - name: List Agility Tools
            type: mcp.ListTools
            server: Agility MCP Server
          - name: OK?
            type: xlrelease.GateTask
            owner: admin

  # Gemini prompt example

  - template: Gemini prompt
    phases:
      - phase: Prompt
        tasks:
          - name: Ask something
            type: mcp.GeminiPrompt
            model: Gemini 2.5 Flash-Lite
            prompt: Say hello in five languages

  # Full example
  - template: Agility summarize user
    phases:
      - phase: User details
        tasks:
          - name: Get current Agility user
            type: mcp.CallTool
            variableMapping:
              result: "${user}"
            server: Agility MCP Server
            tool: get_current_user
          - name: Get name
            type: mcp.GeminiPrompt
            variableMapping:
              response: "${name}"
            model: Gemini 2.5 Flash
            prompt: |-
              Extract the name from the following data. Give me only the full name as a result
              
              ```
              ${user}
              ```
          - name: Get summary
            type: mcp.GeminiPrompt
            variableMapping:
              response: "${summary}"
            model: Gemini 2.5 Flash
            prompt: |-
              Please create a nice summary of the following data
              
              ```
              ${user}
              ```
          - name: Summary for ${name}
            type: xlrelease.Task
            description: ${summary}
    variables:
      - type: xlrelease.StringVariable
        key: user
        requiresValue: false
        showOnReleaseStart: false
        label: User info
        description: JSON info of user
      - type: xlrelease.StringVariable
        key: summary
        requiresValue: false
        showOnReleaseStart: false
        label: User summary
        description: The response from Google Gemini
      - type: xlrelease.StringVariable
        key: name
        requiresValue: false
        showOnReleaseStart: false
        label: User name
        description: Subject of the message.

  # Langchain example

  - template: Langchain demo
    phases:
      - phase: Ask
        tasks:
          - name: Ask about Release
            type: mcp.AgentPrompt
            prompt: Say hello in Dutch
            model: Gemini 2.5 Flash-Lite
          - name: OK?
            type: xlrelease.GateTask
            owner: admin

